### ISSUE TITLE
method 添加返回值

### ISSUE THREAD

**Issue by MBearo** [baidu/san-composition#10]
如题，method方法支持返回值，让函数调用更灵活。

自己改了一点试了下，改动如下：
```js
/**
 * 为组件添加方法
 * 参数可以是key、val两个参数，也可以是对象的形式
 *
 * @param {string|Object} name 数据的key，或者键值对
 * @param {Function} handler 添加的函数
 */
export function method(name, value) {
    if (context.creator) {
        return;
    }

    switch (typeof name) {
    case 'string':
        context.component[name] = value;
        return context.component[name];

    case 'object':
        Object.assign(context.component, name);
        return Object.keys(name).reduce((acc, ccur) => {
            acc[ccur] = context.component[ccur];
            return acc;
        }, {});
    }
}
```
效果如下：
![image](https://user-images.githubusercontent.com/23232655/178490248-e00d9a0e-76d2-4323-9ef6-a4c13f9ac382.png)

想了解一下这么改动有没有不妥的地方

**Comment by errorrik** [comment]
你要这功能有啥用？你如果想要一个函数，直接用不就好了，为啥非要用 method 声明？

```js
    let datasource = data('datasource', {});

    function getRemoteData() {
        send().then(value => {
            datasource.set(value);
        })
    }
    
    watch('xxx', () => {
        getRemoteData();
    });
```

**Comment by MBearo** [comment]
> 你要这功能有啥用？你如果想要一个函数，直接用不就好了，为啥非要用 method 声明？
> 
> ```js
>     let datasource = data('datasource', {});
> 
>     function getRemoteData() {
>         send().then(value => {
>             datasource.set(value);
>         })
>     }
>     
>     watch('xxx', () => {
>         getRemoteData();
>     });
> ```

如果template里同样依赖这个函数呢？

**Comment by errorrik** [comment]
有道理
